# Generated by Django 4.2 on 2023-04-11 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('H', 'Високий'), ('M', 'Середній'), ('L', 'Низький')], default='L', max_length=1)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
